jvm_artifact(
    name="junit-java17",
    group="junit",
    artifact="junit",
    version="4.13.2",
    resolve="java17",
)

jvm_artifact(
    name="junit-java21",
    group="junit",
    artifact="junit",
    version="4.13.2",
    resolve="java21",
)

junit_tests(name="java17", resolve="java17", sources=["**/*.java"])
junit_tests(name="java21", resolve="java21", sources=["**/*.java"])

