"""Shared test fixtures for Clojure backend tests.

This module provides common lockfiles and constants used across tests.
"""

# Clojure version used for tests
CLOJURE_VERSION = "1.12.3"

# Lockfile with Clojure 1.12.3 and correct fingerprints
CLOJURE_LOCKFILE = """\
# This lockfile was autogenerated by Pants. To regenerate, run:
#
#    pants generate-lockfiles
#
# --- BEGIN PANTS LOCKFILE METADATA: DO NOT EDIT OR REMOVE ---
# {
#   "version": 1,
#   "generated_with_requirements": [
#     "org.clojure:clojure:1.12.3,url=not_provided,jar=not_provided"
#   ]
# }
# --- END PANTS LOCKFILE METADATA ---

[[entries]]
file_name = "org.clojure_clojure_1.12.3.jar"
[[entries.directDependencies]]
group = "org.clojure"
artifact = "core.specs.alpha"
version = "0.4.74"
packaging = "jar"

[[entries.directDependencies]]
group = "org.clojure"
artifact = "spec.alpha"
version = "0.5.238"
packaging = "jar"

[[entries.dependencies]]
group = "org.clojure"
artifact = "core.specs.alpha"
version = "0.4.74"
packaging = "jar"

[[entries.dependencies]]
group = "org.clojure"
artifact = "spec.alpha"
version = "0.5.238"
packaging = "jar"


[entries.coord]
group = "org.clojure"
artifact = "clojure"
version = "1.12.3"
packaging = "jar"
[entries.file_digest]
fingerprint = "cb2a1a3db1c2cd76ef4fa4a545d5a65f10b1b48b7f7672f0a109f5476f057166"
serialized_bytes_length = 4230055
[[entries]]
file_name = "org.clojure_core.specs.alpha_0.4.74.jar"
[[entries.directDependencies]]
group = "org.clojure"
artifact = "clojure"
version = "1.12.3"
packaging = "jar"

[[entries.dependencies]]
group = "org.clojure"
artifact = "clojure"
version = "1.12.3"
packaging = "jar"


[entries.coord]
group = "org.clojure"
artifact = "core.specs.alpha"
version = "0.4.74"
packaging = "jar"
[entries.file_digest]
fingerprint = "eb73ac08cf49ba840c88ba67beef11336ca554333d9408808d78946e0feb9ddb"
serialized_bytes_length = 4306
[[entries]]
file_name = "org.clojure_spec.alpha_0.5.238.jar"
[[entries.directDependencies]]
group = "org.clojure"
artifact = "clojure"
version = "1.12.3"
packaging = "jar"

[[entries.dependencies]]
group = "org.clojure"
artifact = "clojure"
version = "1.12.3"
packaging = "jar"


[entries.coord]
group = "org.clojure"
artifact = "spec.alpha"
version = "0.5.238"
packaging = "jar"
[entries.file_digest]
fingerprint = "94cd99b6ea639641f37af4860a643b6ed399ee5a8be5d717cff0b663c8d75077"
serialized_bytes_length = 636643
"""

# Common BUILD file for 3rdparty Clojure dependency
CLOJURE_3RDPARTY_BUILD = f"""\
jvm_artifact(
    name="org.clojure_clojure",
    group="org.clojure",
    artifact="clojure",
    version="{CLOJURE_VERSION}",
)
"""

# Lockfile with Clojure 1.12.3 and JSR305 (for testing provided dependencies)
LOCKFILE_WITH_JSR305 = """\
# This lockfile was autogenerated by Pants. To regenerate, run:
#
#    pants generate-lockfiles
#
# --- BEGIN PANTS LOCKFILE METADATA: DO NOT EDIT OR REMOVE ---
# {
#   "version": 1,
#   "generated_with_requirements": [
#     "com.google.code.findbugs:jsr305:3.0.2,url=not_provided,jar=not_provided",
#     "org.clojure:clojure:1.12.3,url=not_provided,jar=not_provided"
#   ]
# }
# --- END PANTS LOCKFILE METADATA ---

[[entries]]
directDependencies = []
dependencies = []
file_name = "com.google.code.findbugs_jsr305_3.0.2.jar"

[entries.coord]
group = "com.google.code.findbugs"
artifact = "jsr305"
version = "3.0.2"
packaging = "jar"
[entries.file_digest]
fingerprint = "766ad2a0783f2687962c8ad74ceecc38a28b9f72a2d085ee438b7813e928d0c7"
serialized_bytes_length = 19936
[[entries]]
file_name = "org.clojure_clojure_1.12.3.jar"
[[entries.directDependencies]]
group = "org.clojure"
artifact = "core.specs.alpha"
version = "0.4.74"
packaging = "jar"

[[entries.directDependencies]]
group = "org.clojure"
artifact = "spec.alpha"
version = "0.5.238"
packaging = "jar"

[[entries.dependencies]]
group = "org.clojure"
artifact = "core.specs.alpha"
version = "0.4.74"
packaging = "jar"

[[entries.dependencies]]
group = "org.clojure"
artifact = "spec.alpha"
version = "0.5.238"
packaging = "jar"


[entries.coord]
group = "org.clojure"
artifact = "clojure"
version = "1.12.3"
packaging = "jar"
[entries.file_digest]
fingerprint = "cb2a1a3db1c2cd76ef4fa4a545d5a65f10b1b48b7f7672f0a109f5476f057166"
serialized_bytes_length = 4230055
[[entries]]
file_name = "org.clojure_core.specs.alpha_0.4.74.jar"
[[entries.directDependencies]]
group = "org.clojure"
artifact = "clojure"
version = "1.12.3"
packaging = "jar"

[[entries.dependencies]]
group = "org.clojure"
artifact = "clojure"
version = "1.12.3"
packaging = "jar"


[entries.coord]
group = "org.clojure"
artifact = "core.specs.alpha"
version = "0.4.74"
packaging = "jar"
[entries.file_digest]
fingerprint = "eb73ac08cf49ba840c88ba67beef11336ca554333d9408808d78946e0feb9ddb"
serialized_bytes_length = 4306
[[entries]]
file_name = "org.clojure_spec.alpha_0.5.238.jar"
[[entries.directDependencies]]
group = "org.clojure"
artifact = "clojure"
version = "1.12.3"
packaging = "jar"

[[entries.dependencies]]
group = "org.clojure"
artifact = "clojure"
version = "1.12.3"
packaging = "jar"


[entries.coord]
group = "org.clojure"
artifact = "spec.alpha"
version = "0.5.238"
packaging = "jar"
[entries.file_digest]
fingerprint = "94cd99b6ea639641f37af4860a643b6ed399ee5a8be5d717cff0b663c8d75077"
serialized_bytes_length = 636643
"""
