from __future__ import annotations

from textwrap import dedent

import pytest

from clojure_backend.target_types import (
    ClojureSourcesGeneratorTarget,
    ClojureSourceTarget,
    ClojureTestsGeneratorTarget,
    ClojureTestTarget,
)
from clojure_backend.target_types import rules as target_types_rules
from clojure_backend.goals.test import ClojureTestFieldSet, ClojureTestRequest
from clojure_backend.goals.test import rules as test_runner_rules
from clojure_backend import compile_clj
from pants.backend.java.target_types import JavaSourcesGeneratorTarget
from pants.core.goals.test import TestResult
from pants.core.util_rules import config_files, source_files, stripped_source_files, system_binaries
from pants.engine.addresses import Address
from pants.engine.rules import QueryRule
from pants.jvm import classpath, jvm_common, non_jvm_dependencies
from pants.jvm.goals import lockfile
from pants.jvm.resolve.coursier_fetch import rules as coursier_fetch_rules
from pants.jvm.resolve.coursier_setup import rules as coursier_setup_rules
from pants.jvm.target_types import JvmArtifactTarget
from pants.jvm.util_rules import rules as jdk_util_rules
from pants.testutil.rule_runner import PYTHON_BOOTSTRAP_ENV, QueryRule, RuleRunner


@pytest.fixture
def rule_runner() -> RuleRunner:
    rule_runner = RuleRunner(
        preserve_tmpdirs=True,
        rules=[
            *classpath.rules(),
            *compile_clj.rules(),
            *config_files.rules(),
            *coursier_fetch_rules(),
            *coursier_setup_rules(),
            *jdk_util_rules(),
            *jvm_common.rules(),
            *non_jvm_dependencies.rules(),
            *source_files.rules(),
            *stripped_source_files.rules(),
            *system_binaries.rules(),
            *target_types_rules(),
            *test_runner_rules(),
            *lockfile.rules(),
            QueryRule(TestResult, [ClojureTestRequest.Batch]),
        ],
        target_types=[
            ClojureSourceTarget,
            ClojureSourcesGeneratorTarget,
            ClojureTestTarget,
            ClojureTestsGeneratorTarget,
            JvmArtifactTarget,
            JavaSourcesGeneratorTarget,
        ],
    )
    return rule_runner


_JVM_RESOLVES = {
    "jvm-default": "3rdparty/jvm/default.lock",
}


def run_clojure_test(
    rule_runner: RuleRunner,
    target_name: str,
    relative_file_path: str,
    *,
    extra_args: list[str] | None = None,
) -> TestResult:
    args = [
        f"--jvm-resolves={repr(_JVM_RESOLVES)}",
        "--jvm-default-resolve=jvm-default",
        *(extra_args or []),
    ]
    rule_runner.set_options(args, env_inherit=PYTHON_BOOTSTRAP_ENV)
    tgt = rule_runner.get_target(
        Address(spec_path="", target_name=target_name, relative_file_path=relative_file_path)
    )
    return rule_runner.request(
        TestResult,
        [ClojureTestRequest.Batch("", (ClojureTestFieldSet.create(tgt),), None)],
    )


def test_simple_passing_test(rule_runner: RuleRunner) -> None:
    """Test that a simple passing test succeeds."""
    rule_runner.write_files(
        {
            "3rdparty/jvm/BUILD": dedent(
                """\
                jvm_artifact(
                    name="org.clojure_clojure",
                    group="org.clojure",
                    artifact="clojure",
                    version="1.12.0",
                )
                """
            ),
            "3rdparty/jvm/default.lock": dedent(
                """\
                # This lockfile was autogenerated by Pants. To regenerate, run:
                #
                #    pants generate-lockfiles
                #
                # --- BEGIN PANTS LOCKFILE METADATA: DO NOT EDIT OR REMOVE ---
                # {
                #   "version": 1,
                #   "generated_with_requirements": [
                #     "org.clojure:clojure:1.12.0,url=not_provided,jar=not_provided"
                #   ]
                # }
                # --- END PANTS LOCKFILE METADATA ---

                [[entries]]
                file_name = "org.clojure_clojure_1.12.0.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"

                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.0"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "c45333006441a059ea9fdb1341fc6c1f40b921a10dccd82665311e48a0384763"
                serialized_bytes_length = 4227052
                [[entries]]
                file_name = "org.clojure_core.specs.alpha_0.4.74.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.0"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.0"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "eb73ac08cf49ba840c88ba67beef11336ca554333d9408808d78946e0feb9ddb"
                serialized_bytes_length = 4306
                [[entries]]
                file_name = "org.clojure_spec.alpha_0.5.238.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.0"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.0"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "94cd99b6ea639641f37af4860a643b6ed399ee5a8be5d717cff0b663c8d75077"
                serialized_bytes_length = 636643
                """
            ),
            "BUILD": dedent(
                """\
                clojure_tests(
                    name='tests',
                    dependencies=[
                        '3rdparty/jvm:org.clojure_clojure',
                    ],
                )
                """
            ),
            "example_test.clj": dedent(
                """\
                (ns example-test
                  (:require [clojure.test :refer [deftest is testing]]))

                (deftest test-addition
                  (testing "Basic addition"
                    (is (= 4 (+ 2 2)))
                    (is (= 0 (+ -1 1)))))
                """
            ),
        }
    )

    result = run_clojure_test(rule_runner, "tests", "example_test.clj")

    assert result.exit_code == 0
    stdout_text = result.stdout_bytes.decode()
    assert "test-addition" in stdout_text or "example-test" in stdout_text


def test_simple_failing_test(rule_runner: RuleRunner) -> None:
    """Test that a failing test returns non-zero exit code."""
    rule_runner.write_files(
        {
            "3rdparty/jvm/BUILD": dedent(
                """\
                jvm_artifact(
                    name="org.clojure_clojure",
                    group="org.clojure",
                    artifact="clojure",
                    version="1.12.0",
                )
                """
            ),
            "3rdparty/jvm/default.lock": dedent(
                """\
                # This lockfile was autogenerated by Pants. To regenerate, run:
                #
                #    pants generate-lockfiles
                #
                # --- BEGIN PANTS LOCKFILE METADATA: DO NOT EDIT OR REMOVE ---
                # {
                #   "version": 1,
                #   "generated_with_requirements": [
                #     "org.clojure:clojure:1.12.0,url=not_provided,jar=not_provided"
                #   ]
                # }
                # --- END PANTS LOCKFILE METADATA ---

                [[entries]]
                file_name = "org.clojure_clojure_1.12.0.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"

                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.0"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "c45333006441a059ea9fdb1341fc6c1f40b921a10dccd82665311e48a0384763"
                serialized_bytes_length = 4227052
                [[entries]]
                file_name = "org.clojure_core.specs.alpha_0.4.74.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.0"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.0"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "eb73ac08cf49ba840c88ba67beef11336ca554333d9408808d78946e0feb9ddb"
                serialized_bytes_length = 4306
                [[entries]]
                file_name = "org.clojure_spec.alpha_0.5.238.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.0"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.0"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "94cd99b6ea639641f37af4860a643b6ed399ee5a8be5d717cff0b663c8d75077"
                serialized_bytes_length = 636643
                """
            ),
            "BUILD": dedent(
                """\
                clojure_tests(
                    name='tests',
                    dependencies=[
                        '3rdparty/jvm:org.clojure_clojure',
                    ],
                )
                """
            ),
            "failure_test.clj": dedent(
                """\
                (ns failure-test
                  (:require [clojure.test :refer [deftest is]]))

                (deftest test-failure
                  (is (= 5 (+ 2 2)) "2 + 2 should equal 4, not 5"))
                """
            ),
        }
    )

    result = run_clojure_test(rule_runner, "tests", "failure_test.clj")

    assert result.exit_code != 0
    output = (result.stdout_bytes + result.stderr_bytes).decode()
    assert "FAIL" in output or "failed" in output.lower()


def test_test_with_timeout(rule_runner: RuleRunner) -> None:
    """Test that timeout field is respected."""
    rule_runner.write_files(
        {
            "3rdparty/jvm/BUILD": dedent(
                """\
                jvm_artifact(
                    name="org.clojure_clojure",
                    group="org.clojure",
                    artifact="clojure",
                    version="1.12.0",
                )
                """
            ),
            "3rdparty/jvm/default.lock": dedent(
                """\
                # This lockfile was autogenerated by Pants. To regenerate, run:
                #
                #    pants generate-lockfiles
                #
                # --- BEGIN PANTS LOCKFILE METADATA: DO NOT EDIT OR REMOVE ---
                # {
                #   "version": 1,
                #   "generated_with_requirements": [
                #     "org.clojure:clojure:1.12.0,url=not_provided,jar=not_provided"
                #   ]
                # }
                # --- END PANTS LOCKFILE METADATA ---

                [[entries]]
                file_name = "org.clojure_clojure_1.12.0.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"

                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.0"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "c45333006441a059ea9fdb1341fc6c1f40b921a10dccd82665311e48a0384763"
                serialized_bytes_length = 4227052
                [[entries]]
                file_name = "org.clojure_core.specs.alpha_0.4.74.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.0"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.0"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "core.specs.alpha"
                version = "0.4.74"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "eb73ac08cf49ba840c88ba67beef11336ca554333d9408808d78946e0feb9ddb"
                serialized_bytes_length = 4306
                [[entries]]
                file_name = "org.clojure_spec.alpha_0.5.238.jar"
                [[entries.directDependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.0"
                packaging = "jar"

                [[entries.dependencies]]
                group = "org.clojure"
                artifact = "clojure"
                version = "1.12.0"
                packaging = "jar"


                [entries.coord]
                group = "org.clojure"
                artifact = "spec.alpha"
                version = "0.5.238"
                packaging = "jar"
                [entries.file_digest]
                fingerprint = "94cd99b6ea639641f37af4860a643b6ed399ee5a8be5d717cff0b663c8d75077"
                serialized_bytes_length = 636643
                """
            ),
            "BUILD": dedent(
                """\
                clojure_tests(
                    name='tests',
                    timeout=120,
                    dependencies=[
                        '3rdparty/jvm:org.clojure_clojure',
                    ],
                )
                """
            ),
            "timeout_test.clj": dedent(
                """\
                (ns timeout-test
                  (:require [clojure.test :refer [deftest is]]))

                (deftest test-quick
                  (is (= 4 (+ 2 2))))
                """
            ),
        }
    )

    result = run_clojure_test(rule_runner, "tests", "timeout_test.clj")

    # Should succeed (not timeout)
    assert result.exit_code == 0
