jvm_artifact(
    name="clojure-java17",
    group="org.clojure",
    artifact="clojure",
    version="1.11.0",
    resolve="java17",
)

jvm_artifact(
    name="clojure-java21",
    group="org.clojure",
    artifact="clojure",
    version="1.12.0",
    resolve="java21",
)
