jvm_artifact(
    name="guava-java17",
    group="com.google.guava",
    artifact="guava",
    version="31.1-jre",
    resolve="java17",
)

jvm_artifact(
    name="guava-java21",
    group="com.google.guava",
    artifact="guava",
    version="33.0.0-jre",
    resolve="java21",
)

java_sources(
    name="java17",
    resolve="java17",
    sources=["**/*.java"]
)

java_sources(
    name="java21",
    resolve="java21",
    sources=["**/*.java"]
)
